// CSV(소스 진실)를 빌드 타임에 TS 모듈로 임베드한다.
// JSON import는 Next 서버 빌드에서 에셋 파일로 외부화될 수 있고(→ 워커 런타임 fs 불가로 빈 테이블),
// TS 소스의 배열 리터럴은 webpack이 외부화하지 못해 항상 JS 번들에 인라인된다.
// build / cf:build 가 매번 재생성 → CSV-데이터 드리프트 없음.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "csv-parse/sync";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CSV = path.join(root, "data", "전결_검색테이블_통합.csv");
const TS_OUT = path.join(root, "lib", "tableData.generated.ts");

const csv = fs.readFileSync(CSV, "utf-8");
const rows = parse(csv, { columns: true, skip_empty_lines: true, bom: true });

const banner =
  "// AUTO-GENERATED by scripts/gen-table.mjs — do not edit.\n" +
  "// Source: data/전결_검색테이블_통합.csv (수정 시 `npm run data:build`)\n";
const body =
  "const rows: Record<string, string>[] = " +
  JSON.stringify(rows) +
  ";\nexport default rows;\n";
fs.writeFileSync(TS_OUT, banner + body, "utf-8");
console.log(`gen-table: ${rows.length}행 → ${path.relative(root, TS_OUT)}`);
